#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: true

ati_config:
  ft_ecat_pos: 1
  save_calib_matrix: false
  #calib_mat_file: ../examples/ati_ft6_calib/data/ones.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/cent_ft_81.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/cent_ft_80.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/cog_ft_CM_157.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/cog_ft_CM_147.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_rightFoot_ft_147_sens2.txt
  #calib_mat_file: ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_leftFoot_ft_157_sens2.txt
  dump_log: true

