#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: enp2s0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false

#
ec_boards_base:
  robot_name : centauro
  urdf_config_file : ../configs/centauro_urdf.yaml
  joints_poses_file : ../configs/test_poses.yaml

firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  # all esc
  #slave_pos_list: [1]
  # all CentAC motor
  #slave_pos_list: [-4]
  #slave_pos_list: [7]
  #slave_rId_list: [2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  slave_pos_list: [12,13,14,15,16,17,18,19,20,21,22,23,24,25]
  
 cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0
  power_f28m36:
    m3:
      bin_file: pow_m3.bin
      passwd: 0xF2F2
    c28:
      bin_file: pow_c28.bin
      passwd: 0xF3F3    

#############################
# GENERIC ESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0

HpESC_X:
  sign: 1
  pos_offset: 0

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [0.0, 0.0, 1.0, 0.002, 0.0]

CentAcESC_123:
  sign: 1
  pos_offset: 0
  max_current_A: 5.0
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [0.0, 0.0, 6.0, 0.01, 1.0]

#############################
# waist
#############################

CentAcESC_1:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position:   [180.0 , 0.0 , 1.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 0.5, 0.001, 0.0]
    

##############################
# Right Arm

CentAcESC_2:
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_3:
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_4:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]

CentAcESC_5:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]

CentAcESC_6:
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_7:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_8:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

##############################
# Left Arm
    
CentAcESC_9:
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_10:
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_11:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]
    
CentAcESC_12:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]
    
CentAcESC_13:
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_14:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_15:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

    
##############################
# FrontLeft Leg
    
CentAcESC_71:
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_72:
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_73:
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_74:
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_75:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_76:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [30.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]


##############################
# FrontRight Leg
    
CentAcESC_41:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_42:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_43:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_44:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_45:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_46:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [30.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]


##############################
# HindLeft Leg
    
CentAcESC_61:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_62:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_63:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_64:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_65:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_66:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [30.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

    
##############################
# HindRight Leg

CentAcESC_51:
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_52:
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_53:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_54:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_55:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_56:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [30.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]
    
##############################
# sort of Head
    
LpESC_101:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 1.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]

LpESC_102:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 1.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]

LpESC_103:
  sign: 1
  pos_offset: 0
  pid :
    position: [0.0 , 0.0 , 0.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]
