#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  sync_cycle_time_ns: 1000000
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false

      

#############################
# waist
#############################

CentAcESC_1:
  sign: 1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318
  

##############################
# Right Arm

CentAcESC_2:
  sign: 1
  pos_offset: 45
  upd_params :
  # ...101...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318

CentAcESC_3:
  sign: 1
  pos_offset: 45
  upd_params :
  # ...101...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318

CentAcESC_4:
  sign: 1
  pos_offset: 0
  upd_params :
  # ...102...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.846
    motorTorqueConstant : 0.049
    windingResistance : 0.355

CentAcESC_5:
  sign: 1
  pos_offset: 0
  upd_params :
  # ...102...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.846
    motorTorqueConstant : 0.049
    windingResistance : 0.355

CentAcESC_6:
  sign: -1
  pos_offset: 0
  upd_params :
  # ...103...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.163
    motorTorqueConstant : 0.041
    windingResistance : 0.664

CentAcESC_7:
  sign: 1
  pos_offset: 0
  upd_params :
  # ...103...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.163
    motorTorqueConstant : 0.041
    windingResistance : 0.664

CentAcESC_8:
  sign: 1
  pos_offset: 0
  upd_params :
  # ...104...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.126
    motorTorqueConstant : 0.0236
    windingResistance : 0.698

##############################
# Left Arm
    
CentAcESC_9:
  sign: 1
  pos_offset: -45
  upd_params :
  # ...101...
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318

CentAcESC_10:
  sign: 1
  pos_offset: -45
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318

CentAcESC_11:
  sign: 1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.846
    motorTorqueConstant : 0.049
    windingResistance : 0.355
    
CentAcESC_12:
  sign: 1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.846
    motorTorqueConstant : 0.049
    windingResistance : 0.355
    
CentAcESC_13:
  sign: -1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.163
    motorTorqueConstant : 0.041
    windingResistance : 0.664

CentAcESC_14:
  sign: 1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.163
    motorTorqueConstant : 0.041
    windingResistance : 0.664

CentAcESC_15:
  sign: 1
  pos_offset: 0
  upd_params :
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 0.126
    motorTorqueConstant : 0.0236
    windingResistance : 0.698
