#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false

#
ec_boards_base:
  robot_name : cogimon
  urdf_config_file : ../configs/cogimon_urdf.yaml
  joints_poses_file : ../configs/cogimon_poses.yaml

firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  # all esc
  #slave_pos_list: [1]
  # all CentAC motor
  slave_pos_list: [-4]
  
  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0
  power_f28m36:
    m3:
      bin_file: pow_m3.bin
      passwd: 0xF2F2
    c28:
      bin_file: pow_c28.bin
      passwd: 0xF3F3    

#############################
# GENERIC ESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0

HpESC_X:
  sign: 1
  pos_offset: 0

CentAcESC_X:
  sign: 1
  pos_offset: 0
  #max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: false

  pid :
    position: [2500.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [0.0, 0.0, 1.0, 0.002, 0.0]


#############################
# Right tibia
#############################

CentAcESC_45:
  sign: -1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false
  pid :
    position:   [2000.0 , 0.0 , 30.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 0.5, 0.001, 0.0]

CentAcESC_46:
  sign: 1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false
  pid :
    position:   [2000.0 , 0.0 , 30.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 0.5, 0.001, 0.0]

#############################
# Left tibia
#############################

CentAcESC_55:
  sign: -1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false
  pid :
    position:   [2000.0 , 0.0 , 30.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 0.5, 0.001, 0.0]

CentAcESC_56:
  sign: 1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false
  pid :
    position:   [2000.0 , 0.0 , 30.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 0.5, 0.001, 0.0]

