#

ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 0
  power_off_boards: false
  
firmware_update:
  #
  fw_path: ../firmware/  
  # slave robot id
  # legs motors
  #slave_rId_list: [41,41,42,43,44,45,46,51,52,53,54,55,56]
  # upper body big medium motors
  #slave_rId_list: [31,31,32,33,11,12,13,14,21,22,23,24]
  # upper body arms
  #slave_rId_list: [11,12,13,14,21,22,23,24]
  #slave_pos_list: [12,19,29,38]
  # small motors
  #slave_rId_list: [15,16,17,19,25,26,27,29,1,2]
  #slave_pos_list: [5]
  #slave_pos_list: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
  slave_rId_list: [1,1,2,15,16,17,19,25,26,27,29]
  #slave_pos_list: [0]
  
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef

#############################
# GENERIC LpESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#############################
# LOWER BODY
#############################

#
LpESC_2:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_3:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_4:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_5:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_6:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_7:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_8:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_9:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_10:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_11:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_12:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_13:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_14:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

#
LpESC_15:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]


#############################
# UPPERBODY
#############################

#
LpESC_1:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]
