#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_offset_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false

#
ec_boards_base:
  create_pipes: true

#############################
# GENERIC LpESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
    
####################################
# Right arm
####################################

# shoulder
LpESC_16:
  sign: 1
  pos_offset: 0

# shoulder flap
LpESC_17:
  sign: 1
  pos_offset: 0

# arm rotate
LpESC_18:
  sign: 1
  pos_offset: 0

# elbow
LpESC_19:
  sign: 1
  pos_offset: 0

####################################
# Left arm
####################################

# shoulder
LpESC_20:
  sign: 1
  pos_offset: 0

# shoulder flap
LpESC_21:
  sign: 1
  pos_offset: 0

# arm rotate
LpESC_22:
  sign: 1
  pos_offset: 0

# elbow
LpESC_23:
  sign: 1
  pos_offset: 0

####################################
# Right forearm
####################################

# wrist rotate
LpESC_26:
  sign: 1
  pos_offset: 0
  pid :
    position: [ 100000.0 , 0.0 , 0.0 ]

# wrist up/down
LpESC_27:
  sign: 1
  pos_offset: 0
  pid :
    position: [ 30000.0 , 0.0 , 0.0 ]

# wrist left/right
LpESC_28:
  sign: 1
  pos_offset: 0
  pid :
    position: [ 30000.0 , 0.0 , 0.0 ]

####################################
# Left forearm
####################################

# wrist rotate
LpESC_29:
  sign: 1
  pos_offset: 0
  pid :
    position: [ 100000.0 , 0.0 , 0.0 ]
    
# wrist up/down
LpESC_30:
  sign: 1
  pos_offset: 0
  pid :
    position: [30000.0 , 0.0 , 0.0 ]

# wrist left/right
LpESC_31:
  sign: 1
  pos_offset: 0
  pid :
    position: [30000.0 , 0.0 , 0.0, ]

    