#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false


#############################
# GENERIC LpESC config
#############################

#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

HpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [250.0 , 0.0 , 5.0]
    mix_position: [250.0 , 0.0 , 5.0]

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [220.0 , 0.0 , 5.0]

