#
ec_boards_base:
  create_pipes: true

ec_board_ctrl:
  eth_iface: eth2
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  #sync_cycle_offset_ns: 3000000000
  sync_cycle_offset_ns: 0
  power_off_boards: false
