#

ec_board_ctrl:
  eth_iface: eth1
  #eth_iface: rteth0
  #eth_iface: enp2s0
  #eth_iface: enp64s0
  #sync_cycle_time_ns: 500000
  #sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 50000000
  #sync_cycle_time_ns: 0
  #sync_cycle_offset_ns: 4000000000
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false
 
ec_boards_base:
  urdf_config_file: ../configs/centauro_urdf.yaml
  joints_poses_file : ../configs/test_poses.yaml


Lxm32i_A:
  # operation mode : abs_pos, rel_pos 
  OpMode    : abs_pos
  PPv_target: 400
  RAMP_v_acc: 80000
  RAMP_v_dec: 80000
  #set_points: [0,10000,-10000,20000,-20000,30000,-30000,20000,-20000,10000,-10000]
  set_points: [32768,-32768,65536,-65536,131072,-131072,65536,-65536,32768,-32768]
  
Lxm32i_B:
  PPv_target: 2500
  RAMP_v_acc: 50000
  RAMP_v_dec: 50000

Lxm32i_C:
  PPv_target: 2500
  RAMP_v_acc: 50000
  RAMP_v_dec: 50000
