
firmware_update:
  #fw_path: ../firmware/
  #fw_path: ../examples/fw_update/fw_pdo56/
  fw_path: ../examples/fw_update/fw_test/
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  #slave_pos_list: [-4]
  slave_pos_list: [1]
  
  big_motor:
    bin_file: BigMotor.bin
    passwd: 0xb001
  medium_motor:
    bin_file: MedMotor.bin
    passwd: 0xb002
  power_hub:
    bin_file: Pow_Hub.bin
    passwd: 0xb003
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef
  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0
  power_f28m36:
    m3:
      bin_file: pow_m3.bin
      passwd: 0xF2F2
    c28:
      bin_file: pow_c28.bin
      passwd: 0xF3F3
  test_f28m36:
    m3:
      bin_file: soes_m3.bin
      passwd: 0xF0F0
    c28:
      bin_file: soes_c28.bin
      passwd: 0xF1F1

      
      
flash_files:
  bin_path: /tmp/
  # all CentAC motor
  slave_pos_list: [-4]

  cent_AC: 
    m3: 
        params: 
            bin_file: flash_params 
            passwd: 0xF001 
            size_byte: 131072 
        torque_cal: 
            bin_file: torque_calib 
            passwd: 0xF002 
            size_byte: 32768 

  test_f28m36:
    m3:
        params:
            bin_file: flash_params.bin
            passwd: 0xF001
        torque_cal:
            bin_file: torque_calib.bin
            passwd: 0xF002
  
  