#
ec_boards_base:
  create_pipes: true

ec_board_ctrl:
  eth_iface: eth1
  #sync_cycle_time_ns: 500000
  #sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 50000000
  #sync_cycle_time_ns: 0
  #sync_cycle_offset_ns: 4000000000
  sync_cycle_offset_ns: 0
  power_off_boards: false
 
firmware_update:
  #fw_path: ../firmware/
  #fw_path: ../examples/fw_update/fw_pdo56/
  fw_path: ../examples/fw_update/fw_test/
  #slave_pos_list: [3]
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  
  big_motor:
    bin_file: BigMotor.bin
    passwd: 0xb001
  medium_motor:
    bin_file: MedMotor.bin
    passwd: 0xb002
  power_hub:
    bin_file: Pow_Hub.bin
    passwd: 0xb003
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef

#############################
# GENERIC LpESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

LpSphESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

LpSphBrkESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

HpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 10.0 , 1.0]
