#
ec_boards_base:
  create_pipes: true

ec_board_ctrl:
  eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 0
  power_off_boards: false
  

#############################
# GENERIC LpESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]