#

ec_board_ctrl:
  eth_iface: eth1
  #eth_iface: enp2s0
  #sync_cycle_time_ns: 500000
  #sync_cycle_time_ns: 1000000
  sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 50000000
  #sync_cycle_time_ns: 0
  #sync_cycle_offset_ns: 4000000000
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false
 
ec_boards_base:
  urdf_config_file: ../configs/centauro_urdf.yaml
  joints_poses_file : ../configs/test_poses.yaml

firmware_update:
  #fw_path: ../firmware/
  #fw_path: ../examples/fw_update/fw_pdo56/
  fw_path: ../examples/fw_update/fw_test/
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  #slave_pos_list: [-4]
  slave_pos_list: [1]
  
  big_motor:
    bin_file: BigMotor.bin
    passwd: 0xb001
  medium_motor:
    bin_file: MedMotor.bin
    passwd: 0xb002
  power_hub:
    bin_file: Pow_Hub.bin
    passwd: 0xb003
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef
  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0
  power_f28m36:
    m3:
      bin_file: pow_m3.bin
      passwd: 0xF2F2
    c28:
      bin_file: pow_c28.bin
      passwd: 0xF3F3
  test_f28m36:
    m3:
      bin_file: soes_m3.bin
      passwd: 0xF0F0
    c28:
      bin_file: soes_c28.bin
      passwd: 0xF1F1
      
#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

HpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 10.0]
    mix_position: [250.0 , 0.0 , 5.0]

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [220.0 , 0.0 , 5.0]

  NO_upd_params :
    # A0 
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318
  
  NO_aux_pdo : # names defined in SDO index 0x8002 
     rd :  [ pos_ref_fb, iq_ref_fb, id_ref_fb ]
     wr :  [ ]
     wrd : [ "iq_offset&&iq_out_fb" ]
     
#############################
# TEST JOINT
#############################

# B14
HpESC_101:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]
  gear_ratio: GR_120

# M17
HpESC_102:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]
  gear_ratio: GR_100


LpESC_999:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0, 0.0, 1.0]
    mix_position: [2500.0,0.005,100.0]
    

#################################

    
LpHandESC_1:
  sign: 1
  pos_offset: 0
  pid :
    position: [60000.0 , 0.0 , 20.0]

LpHandESC_2:
  sign: 1
  pos_offset: 0
  pid :
    position: [60000.0 , 0.0 , 20.0]

LpHandESC_3:
  sign: 1
  pos_offset: 0
  pid :
    position: [300000.0 , 0.0 , 10.0]
