#
ec_board_ctrl:
  #eth_iface: eth1
  #eth_iface: enp2s0
  #eth_iface: enp33s0
  eth_iface: enp35s0
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 50000000
  #sync_cycle_time_ns: 0
  #sync_cycle_offset_ns: 0
  #sync_cycle_offset_ns: 4000000000
  sync_cycle_offset_ns: 1000000000
  sync_point_ns : 500000
  power_off_boards : false
  reset_micro : true

ec_boards_base :
  app_mode : run_mode
  #app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  fault_power_off : true
  # only for CentAcESC , Ft6msp432 and TestESC
  #use_ecat_pos_as_id : true
  #
  urdf_config_file : ../configs/centauro_urdf.yaml
  joints_poses_file : ../configs/test_poses.yaml

zmq_pub :
  base_port : 9000
  uri: "tcp://*:"
  fd_timeout_us : 100000 
  
microCTRL_stuff: ../configs/microCTRL_config.yaml
      
ati_config :
  ati_ip_addr : 192.168.1.1
  ft_ecat_pos : 1
  save_calib_matrix : false
  #calib_mat_file : ../examples/ati_ft6_calib/data/ones.txt
  calib_mat_file : ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_right_Foot_ft_147_sens8.txt
  dump_log : true

#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HpESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 10.0]
    mix_position: [250.0 , 0.0 , 5.0]

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 5.0
  enable_sandbox: false
  enable_pos_filter: false
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    #impedance:  [0.0, 0.0, 5.0, 0.01, 0.8]
    impedance:  [30.0, 5, 5.0, 0.01, 0.8]
   
  NO_upd_params :
    Hardware_config : 0x3236
    Joint_robot_id : 88
    Serial_Number_A : 3
    
  NO_upd_params :
    posRefFilterFreq : 1
    motorDirectInductance : 0
    motorQuadratureInductance : 0
    crossTermCCGain : 0

  NO_upd_params :
    # A0 
    DOB_filterFrequencyHz : 10
    voltageFeedforward : 1.0
    backEmfCompensation : 0.8
    directTorqueFeedbackGain : 1.0
    sandBoxAngle : 0.05
    sandBoxFriction : 0.5
    gearedMotorInertia : 1.181
    motorTorqueConstant : 0.078
    windingResistance : 0.318
  
  aux_pdo : # names defined in SDO index 0x8002 
     _rd :  [ pos_ref_fb, iq_ref_fb, id_ref_fb ]
     _wr :  [ ]
     _wrd : [ "iq_offset&&iq_out_fb" ]
     wrd : [ "ts&&rtt" ]

Ft6Msp432ESC_X:
  analog_sample_freq_HZ: 10000

#############################
# TEST JOINT
#############################

# B14
HpESC_101:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]
  gear_ratio: GR_120

# M17
HpESC_102:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]
  gear_ratio: GR_100


LpESC_999:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0, 0.0, 1.0]
    mix_position: [2500.0,0.005,100.0]
    

#################################

    
LpHandESC_1:
  sign: 1
  pos_offset: 0
  pid :
    position: [60000.0 , 0.0 , 20.0]

LpHandESC_2:
  sign: 1
  pos_offset: 0
  pid :
    position: [60000.0 , 0.0 , 20.0]

LpHandESC_3:
  sign: 1
  pos_offset: 0
  pid :
    position: [300000.0 , 0.0 , 10.0]
