
# #####################################
# map of sequences of string
# macro sequences id @robot_mcs  

joint_group_by_controller :
    position_ctrl :
        [ HEAD_R, TEST_101, TEST_102, TEST_103 ]
    impedance_ctrl :
        [ ]
    velocity_ctrl :
        [ ]
    direct_ctrl :
        [ ]
    # always subtract from above sets    
    NO_ctrl :
        [ ]


# #####################################

trjs_map :
  #start@home :
  home@pos1@home : 
    - [home, 0]
    - [pos_1, 3]
    - [home, 6]
  home@pos1@pos2@home : 
    - [home, 0]
    - [pos_1, 3]
    - [pos_2, 6]
    - [home, 9]
  home@pos1@pos2@pos3@home : 
    - [home, 0]
    - [pos_1, 3]
    - [pos_2, 6]
    - [pos_3, 9]
    - [home, 12]

    
# #####################################
# position in degrees
pos_map :

    home :
        HEAD_R :     0.0
        TEST_101 :   0.0
        TEST_102 :   0.0
        TEST_103 :   0.0

    pos_1 :
        TEST_101 :  45.0
        TEST_102 :  45.0
        TEST_103 :  45.0
        HEAD_R :    20.0
        
    pos_2 :
        TEST_101 :  90.0
        TEST_102 :  90.0
        TEST_103 :  90.0
        HEAD_R :    30.0

    pos_3 :
        TEST_101 : -90.0
        TEST_102 : -90.0
        TEST_103 : -90.0
        HEAD_R :    10.0
  