#
ec_boards_base:
  create_pipes: true
  
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #eth_iface: eth0
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 0
  power_off_boards: false
  
firmware_update:
  #
  #fw_path: ../firmware/  
  fw_path: ../examples/fw_update/fw_pdo56/reunion/  
  #fw_path: ../examples/fw_update/fw_pdo56/walkman_jorn/  
  #fw_path: ../examples/fw_update/fw_pdo56/walkman_up/  
  #fw_path: ../examples/fw_update/fw_pdo56/walkman_NOup/  
  
  # legs+torso_roll UPGRADED motors
  #slave_rId_list: [33,41,42,43,44,45,46,51,52,53,54,55,56]
  # upper body NOT UPGRADED motors
  #slave_rId_list: [31,32,11,12,13,14,21,22,23,24]
  # upper body arms
  #slave_rId_list: [11,12,13,14,21,22,23,24]
  # small motors
  #slave_rId_list: [15,16,17,19,25,26,27,29,1,2]
  slave_pos_list: [1,2]
  #slave_pos_list: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
  #slave_rId_list: [1,2,15,16,17,19,25,26,27,29]
  #slave_rId_list: [32,33]
  #slave_pos_list: [4,5,6,7,8,9,17,18,19,20,27]
  #####################################################3
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  
  big_motor:
    bin_file: BigMotor.bin
    passwd: 0xb001
  medium_motor:
    bin_file: MedMotor.bin
    passwd: 0xb002
  power_hub:
    bin_file: Pow_Hub.bin
    passwd: 0xb003
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef

    
#############################
# torque upgrade params
#############################
  
GR_80: 
    Motor_Inertia: 0.3923
    Inv_Motor_Inertia: 2.5489
    Observer_Cut_Off: 5.0
    Inv_Geared_Torque_Constant: 0.1068
    Geared_Torque_Constant: 9.36
    Winding_Resistance: 0.356
    Voltage_Feedforward: 1.0
    BackEmf_Compensation: 0.8

GR_100: 
    Motor_Inertia: 0.6130
    Inv_Motor_Inertia: 1.6313
    Observer_Cut_Off: 5.0
    Inv_Geared_Torque_Constant: 0.0855
    Geared_Torque_Constant: 11.7
    Winding_Resistance: 0.356
    Voltage_Feedforward: 1.0
    BackEmf_Compensation: 0.8

GR_120: 
    Motor_Inertia: 0.8827
    InvMotor_Inertia: 1.1329
    Observer_Cut_Off: 5.0
    Inv_Geared_Torque_Constant: 0.0712
    Geared_Torque_Constant: 14.04
    Winding_Resistance: 0.356
    Voltage_Feedforward: 1.0
    BackEmf_Compensation: 0.8

GR_160: 
    Motor_Inertia: 1.5693
    Inv_Motor_Inertia: 0.6372
    Observer_Cut_Off: 5.0
    Inv_Geared_Torque_Constant: 0.0534
    Geared_Torque_Constant: 18.72
    Winding_Resistance: 0.356
    Voltage_Feedforward: 1.0
    BackEmf_Compensation: 0.8

#############################
# HEAD
#############################

#
LpESC_1:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#
LpESC_2:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]

# RL_H_Y = 42
HpESC_42:
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_H_P = 43
HpESC_43:
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# RL_K = 44
HpESC_44:
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_P = 45
HpESC_45:
  sign: -1
  pos_offset: 20
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_R = 46
HpESC_46:
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_Y = 51
HpESC_51:
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_H_R = 52
HpESC_52:
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_H_P = 53
HpESC_53:
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_K = 54
HpESC_54:
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_A_P = 55
HpESC_55:
  sign: 1
  pos_offset: 20
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_A_R = 56
HpESC_56:
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]


#############################
# RIGHT ARM
#############################

# RA_SH_1 = 11
HpESC_11:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_120

# RA_SH_2 = 12
HpESC_12:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_120

# RA_SH_3 = 13
HpESC_13:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_80

# RA_EL_ = 14
HpESC_14:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_80

# RA_WR_1 = 15
LpESC_15:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_WR_2 = 16
LpESC_16:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_WR_3 = 17
LpESC_17:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_HA = 19
LpESC_19:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#############################
# LEFT ARM
#############################

# LA_SH_1 = 21
HpESC_21:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_120

# LA_SH_2 = 22
HpESC_22:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_120

# LA_SH_3 = 23
HpESC_23:
  sign: 1
  pos_offset: 0
  pid :
    position: [50.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    impedance:  [100.0, 10.0, 3.0, 0.03, 0.8]
  #gear_ratio: GR_80
  gear_ratio: GR_100

# LA_EL = 24
HpESC_24:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
  gear_ratio: GR_80

# LA_WR_1 = 25
LpESC_25:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_2 = 26
LpESC_26:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_3 = 27
LpESC_27:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#############################
# WAIST
#############################

# WST_P = 31
HpESC_31:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# WST_R = 32
HpESC_32:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# WST_Y = 33
HpESC_33:
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]


#############################
# TEST JOINT
#############################

HpESC_666:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0, 0.0, 1.0]
    mix_position: [2500.0, 0.005, 10.0]

HpESC_1000:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0, 0.0, 1.0]
    mix_position: [2500.0, 0.005, 100.0]


LpESC_999:
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0, 0.0, 1.0]
    mix_position: [2500.0,0.005,100.0]
