
# #####################################
# map of sequences of string
# macro sequences id @robot_mcs  

joint_group_by_controller :
    position_ctrl :
        [ '@robot_mcs' ]
    impedance_ctrl :
        [ ]
    velocity_ctrl :
        [ ]
    direct_ctrl :
        [ ]
    # always subtract from above sets    
    NO_ctrl :
        [ WAIST_R ]

# #####################################
# map of sequences of pairs
trjs_map :
#  start2home :
#    - [start, 0]
#    - [home,  5]
  home2jump2home : 
    - [home, 0]
    - [jump, 3]
    - [home, 6]
  home2arms_back2home : 
    - [home, 0]
    - [arms_back, 3]
    - [home, 6]
  home2high_guard2home : 
    - [home, 0]
    - [high_guard, 2]
    - [home, 4]

    
# #####################################
# position in degrees
pos_map :

    home :
        HEAD_R :     0.0
        HEAD_P :     0.0
        # waist
        WAIST_Y :    0.0
        WAIST_P :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :   65.0
        RA_SH_2 :  -70.0
        RA_SH_3 :   20.0
        RA_EL :   -150.0
        RA_WR_1 :    0.0
        RA_WR_2 :    0.0
        RA_WR_3 :   35.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :   65.0
        LA_SH_2 :   70.0
        LA_SH_3 :  -20.0
        LA_EL :   -150.0   
        LA_WR_1 :    0.0
        LA_WR_2 :    0.0
        LA_WR_3 :  -35.0
        LA_HA :      0.0
        # right leg
        RL_H_R :     2.2
        RL_H_Y :     0.15
        RL_H_P :   -17.0
        RL_K :      33.0
        RL_A_P :    16.0
        RL_A_R :    -2.0
        # left leg
        LL_H_R :    -2.2  
        LL_H_Y :    -0.15 
        LL_H_P :   -17.0
        LL_K :      33.0
        LL_A_P :    16.0
        LL_A_R :    -2.0

    jump :
        HEAD_R :     0.0
        HEAD_P :     0.0
        # waist
        WAIST_Y :    0.0
        WAIST_P :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :   20.0
        RA_SH_2 :  -20.0
        RA_SH_3 :  -40.0
        RA_EL :    -50.0
        RA_WR_1 :  -20.0
        RA_WR_2 :  -30.0
        RA_WR_3 :  -40.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :   20.0
        LA_SH_2 :   20.0
        LA_SH_3 :   40.0
        LA_EL :    -50.0   
        LA_WR_1 :   20.0
        LA_WR_2 :  -30.0
        LA_WR_3 :   40.0
        LA_HA :      0.0
        # right leg
        RL_H_R :   -15.0
        RL_H_Y :   -35.0
        RL_H_P :   -80.0
        RL_K :      80.0
        RL_A_P :   -20.0
        RL_A_R :    20.0
        # left leg
        LL_H_R :    15.0  
        LL_H_Y :    35.0 
        LL_H_P :   -80.0
        LL_K :      80.0
        LL_A_P :   -20.0
        LL_A_R :   -20.0

    arms_back :
        HEAD_R :     0.0
        HEAD_P :     0.0
        # waist
        WAIST_Y :    0.0
        WAIST_P :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :   88.0
        RA_SH_2 :  -70.0
        RA_SH_3 :   30.0
        RA_EL :     -5.0
        RA_WR_1 :    0.0
        RA_WR_2 :    0.0
        RA_WR_3 :    0.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :   88.0
        LA_SH_2 :   70.0
        LA_SH_3 :  -30.0
        LA_EL :     -5.0   
        LA_WR_1 :    0.0
        LA_WR_2 :    0.0
        LA_WR_3 :    0.0
        LA_HA :      0.0
        # right leg
        RL_H_R :   -15.0
        RL_H_Y :     0.2
        RL_H_P :   -90.0
        RL_K :      90.0
        RL_A_P :   -20.0
        RL_A_R :    20.0
        # left leg
        LL_H_R :    15.0  
        LL_H_Y :    -0.2 
        LL_H_P :   -90.0
        LL_K :      90.0
        LL_A_P :   -20.0
        LL_A_R :   -20.0

    high_guard :
        HEAD_R :     0.0
        HEAD_P :     0.0
        # waist
        WAIST_Y :    0.0
        WAIST_P :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :  -20.0
        RA_SH_2 :  -70.0
        RA_SH_3 :  -30.0
        RA_EL :   -150.0
        RA_WR_1 :   10.0
        RA_WR_2 :    0.0
        RA_WR_3 :   30.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :  -20.0
        LA_SH_2 :   70.0
        LA_SH_3 :   30.0
        LA_EL :   -150.0   
        LA_WR_1 :  -10.0
        LA_WR_2 :    0.0
        LA_WR_3 :  -30.0
        LA_HA :      0.0
        # right leg
        RL_H_R :     2.2
        RL_H_Y :     0.15
        RL_H_P :   -17.0
        RL_K :      33.0
        RL_A_P :    16.0
        RL_A_R :    -2.0
        # left leg
        LL_H_R :    -2.2  
        LL_H_Y :    -0.15 
        LL_H_P :   -17.0
        LL_K :      33.0
        LL_A_P :    16.0
        LL_A_R :    -2.0
  