#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #eth_iface: enp35s0
  #eth_iface: eth0
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 0
  power_off_boards: false

ec_boards_base :
  robot_name : walkimon
  urdf_config_file : ../configs/walkman_urdf.yaml
  joints_poses_file : ../configs/walkimon_poses.yaml
  
  
  
firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  
  #slave_pos_list: [1]
  #####################################################
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  slave_pos_list: [-4]
  
  big_motor:
    bin_file: BigMotor.bin
    passwd: 0xb001
  medium_motor:
    bin_file: MedMotor.bin
    passwd: 0xb002
  power_hub:
    bin_file: Pow_Hub.bin
    passwd: 0xb003
  small_motor:
    bin_file: mc_tm4c.bin
    passwd: 0xbeef
  force_torque_6:
    bin_file: FT6.bin
    passwd: 0xbeef
  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    NO_c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0
  power_f28m36:
    m3:
      bin_file: pow_m3.bin
      passwd: 0xF2F2
    c28:
      bin_file: pow_c28.bin
      passwd: 0xF3F3

    

#############################
# HEAD & HANDS
#############################

#
LpESC_1:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#
LpESC_2:
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_HA = 19
LpESC_19:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]

# RL_H_Y = 42
HpESC_42:
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_H_P = 43
HpESC_43:
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# RL_K = 44
HpESC_44:
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_P = 45
HpESC_45:
  sign: -1
  pos_offset: 20
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_R = 46
HpESC_46:
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_Y = 51
HpESC_51:
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_H_R = 52
HpESC_52:
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_H_P = 53
HpESC_53:
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_K = 54
HpESC_54:
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 5.0, 0.01, 0.8]

# LL_A_P = 55
HpESC_55:
  sign: 1
  pos_offset: 20
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_A_R = 56
HpESC_56:
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]


##############################
# RIGHT ARM
##############################

CentAcESC_11:
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_12:
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_13:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]

CentAcESC_14:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]

CentAcESC_15:
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_16:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_17:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

##############################
# LEFT ARM
##############################
    
CentAcESC_21:
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_22:
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_23:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]
    
CentAcESC_24:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]
    
CentAcESC_25:
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_26:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_27:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

#############################
# WAIST
#############################

CentAcESC_31:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_32:
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]


