
# #####################################
# map of sequences of string
# macro sequences id @robot_mcs  

joint_group_by_controller :
    position_ctrl :
        [ '@robot_mcs']
        #[ '@robot_left_arm']
        #[ '@robot_right_arm']
        #[ RA_HA , LA_HA ]
    impedance_ctrl :
        [ ]
    velocity_ctrl :
        [ ]
    direct_ctrl :
        [ ]
    # always subtract from above sets    
    NO_ctrl :
        [ WAIST_Y, WAIST_R ]

# #####################################
# map of sequences of pairs
trjs_map :
#  start2home :
#    - [start, 0]
#    - [home,  5]
   home2fw2back2fw2home :
     - [home,  0]
     - [fw,    3]
     - [back,  7]
     - [fw,   10]
     - [home, 13]
     
# #####################################
# position in degrees
pos_map :

    home :
        HEAD_P :     0.0
        HEAD_Y :     0.0
        # waist
        WAIST_Y :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :  -30.0
        RA_SH_2 :   30.0
        RA_SH_3 :   10.0
        RA_EL :     60.0
        RA_WR_1 :  -20.0
        RA_WR_2 :   60.0
        RA_WR_3 :   20.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :   30.0
        LA_SH_2 :  -30.0
        LA_SH_3 :  -10.0
        LA_EL :    -60.0   
        LA_WR_1 :   20.0
        LA_WR_2 :  -60.0
        LA_WR_3 :  -20.0
        LA_HA :      0.0
        # right leg
        RL_H_R :     2.2
        RL_H_Y :     0.15
        RL_H_P :   -17.0
        RL_K :      33.0
        RL_A_P :    16.0
        RL_A_R :    -2.0
        # left leg
        LL_H_R :    -2.2  
        LL_H_Y :    -0.15 
        LL_H_P :   -17.0
        LL_K :      33.0
        LL_A_P :    16.0
        LL_A_R :    -2.0

    fw :
        HEAD_P :    10.0
        HEAD_Y :    10.0
        # waist
        WAIST_Y :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :   60.0
        RA_SH_2 :   30.0
        RA_SH_3 :   30.0
        RA_EL :     60.0
        RA_WR_1 :  -20.0
        RA_WR_2 :   90.0
        RA_WR_3 :   20.0
        RA_HA :      0.0
        # left arm
        LA_SH_1 :  -60.0
        LA_SH_2 :  -30.0
        LA_SH_3 :  -30.0
        LA_EL :    -60.0   
        LA_WR_1 :   20.0
        LA_WR_2 :  -90.0
        LA_WR_3 :  -20.0
        LA_HA :      0.0
        # right leg
        RL_H_R :     2.2
        RL_H_Y :     0.15
        RL_H_P :   -17.0
        RL_K :      33.0
        RL_A_P :    16.0
        RL_A_R :    -2.0
        # left leg
        LL_H_R :    -2.2 
        LL_H_Y :    -0.15 
        LL_H_P :   -17.0
        LL_K :      33.0
        LL_A_P :    16.0
        LL_A_R :   -20.0
    back :
        HEAD_P :   -10.0
        HEAD_Y :   -10.0
        # waist
        WAIST_Y :    0.0
        WAIST_R :    0.0
        # right arm
        RA_SH_1 :  -80.0
        RA_SH_2 :   10.0
        RA_SH_3 :   30.0
        RA_EL :    120.0
        RA_WR_1 :  -20.0
        RA_WR_2 :    0.0
        RA_WR_3 :    0.0
        RA_HA :    600.0
        # left arm
        LA_SH_1 :   80.0
        LA_SH_2 :  -10.0
        LA_SH_3 :  -30.0
        LA_EL :   -120.0   
        LA_WR_1 :   20.0
        LA_WR_2 :    0.0
        LA_WR_3 :    0.0
        LA_HA :    600.0
        # right leg
        RL_H_R :     2.2
        RL_H_Y :     0.15
        RL_H_P :   -17.0
        RL_K :      33.0
        RL_A_P :    16.0
        RL_A_R :    -2.0
        # left leg
        LL_H_R :    -2.2  
        LL_H_Y :    -0.15 
        LL_H_P :   -17.0
        LL_K :      33.0
        LL_A_P :    16.0
        LL_A_R :    30.0
  